version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17

  pre_build:
    commands:
      - echo Pre-build phase starting...
      - echo Checking Java and Maven versions
      - java -version
      - mvn -version

  build:
    commands:
      - echo Build phase starting on `date`
      - echo Building with Maven...
      - mvn clean package -DskipTests

  post_build:
    commands:
      - echo Build completed on `date`
      - echo Packaging application...
      - echo "Contents of target directory:"
      - ls -la target/
      - echo "JAR files found:"
      - find target -name "*.jar" -type f

artifacts:
  files:
    - target/*.jar
  name: BuildArtifact
  discard-paths: yes

cache:
  paths:
    - '/root/.m2/**/*'

